config/routes.rb
Rails.application.routes.draw do
  # get 'sessions/new'

  resources :utilizadores
  resources :relationships, only: [:create, :destroy]
  resources :candidatos
  resources :entidades
  resources :oferta_de_empregos
  root    'static_pages#home'
  get     '/alterar_password',  to: 'utilizadores#alterar_password'
  get     '/meu_perfil',        to: 'static_pages#meu_perfil'
  get     '/registo',           to: 'static_pages#registo'
  get     '/login',             to: 'sessions#new'
  post    '/login',             to: 'sessions#create'
  delete  '/logout',            to: 'sessions#destroy'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @ultimas_empresas = Entidade.last(3).reverse
    @ultimos_candidatos = Candidato.last(3).reverse
    @ultimas_ofertas = OfertaDeEmprego.last(3).reverse
  end

  def registo
  end

  def meu_perfil
    if logged_in?
      @cu = current_user
      else
        flash[:danger] = "Por favor efectue login!"
        redirect_back_or login_path
      end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
  <div>
    <div class="col-md-6">
      <%= render 'entidades/ultimas_ofertas' %>
    </div>
    <div class="col-md-6">
      <%= render 'candidatos/ultimos_candidatos' %>
    </div>
    <!-- <div class="col-md-6">
      <h2>Notícias</h2>
    </div> -->
  </div>

  <div>
    <div class="col-md-6">
      <%= render 'entidades/ultimas_empresas' %>
    </div>
  </div>

app/views/static_pages/meu_perfil.html.erb
<div>
  <% @cu_meta_type = @cu.meta_type %>
  <% if @cu_meta_type == "Candidato" %>
    <%= render 'candidatos/meu_perfil' %>
    <% else %>
    <% if @cu_meta_type == "Entidade" %>
      <%= render 'entidades/meu_perfil' %>
    <% end %>
  <% end %>
</div>

app/views/static_pages/registo.html.erb
<h1>Novo Registo</h1>

<div class="registo">
  <div>
    <%= link_to "Sou uma entidade", new_entidade_path, class: "btn btn-default" %>
  </div>
  <div>
    <%= link_to "Sou um candidato", new_candidato_path, class: "btn btn-default"%>
  </div>
</div>