config/routes.rb
Rails.application.routes.draw do
  # get 'sessions/new'

  resources :utilizadores
  resources :relationships, only: [:create, :destroy]
  resources :candidatos
  resources :entidades
  resources :oferta_de_empregos
  root    'static_pages#home'
  get     '/alterar_password',  to: 'utilizadores#alterar_password'
  get     '/meu_perfil',        to: 'static_pages#meu_perfil'
  get     '/registo',           to: 'static_pages#registo'
  get     '/login',             to: 'sessions#new'
  post    '/login',             to: 'sessions#create'
  delete  '/logout',            to: 'sessions#destroy'
end

app/models/entidade.rb
class Entidade < ApplicationRecord
  has_many :oferta_de_empregos, dependent: :destroy
  has_one :utilizador, as: :meta, dependent: :destroy
  accepts_nested_attributes_for :utilizador


end

app/controllers/entidades_controller.rb
class EntidadesController < ApplicationController
  before_action :set_entidade, only: [:show, :edit, :update, :destroy]
  include ApplicationHelper
  include SessionsHelper

  # GET /entidades
  # GET /entidades.json
  def index
    if logged_in?
      @entidades = Entidade.all.paginate(page: params[:page], per_page: 10)
    else
      flash[:danger] = "Por favor efectue login!"
      redirect_to login_path
    end
  end

  # GET /entidades/1
  # GET /entidades/1.json
  def show
    if !logged_in?
      flash[:danger] = "Por favor efectue login!"
      redirect_to login_path
    end
  end

  # GET /entidades/new
  def new
    @entidade = Entidade.new
    @entidade.build_utilizador
  end

  # GET /entidades/1/edit
  def edit
    authorized?("Entidade")
  end

  # POST /entidades
  # POST /entidades.json
  def create
    @entidade = Entidade.new(entidade_params)
    respond_to do |format|
      if @entidade.save
        format.html { redirect_to @entidade, notice: 'Entidade was successfully created.' }
        format.json { render :show, status: :created, location: @entidade }
      else
        format.html { render :new }
        format.json { render json: @entidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entidades/1
  # PATCH/PUT /entidades/1.json
  def update
    if authorized?("Entidade")
      respond_to do |format|
        if @entidade.update(entidade_params)
          log_in(@entidade.utilizador)
          format.html { redirect_to @entidade, notice: 'Entidade actualizado com sucesso.' }
          format.json { render :show, status: :ok, location: @entidade }
        else
          format.html { render :edit }
          format.json { render json: @entidade.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /entidades/1
  # DELETE /entidades/1.json
  def destroy
    if authorized?("Entidade")
      @entidade.destroy
      respond_to do |format|
        format.html { redirect_to entidades_url, notice: 'Entidade was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entidade
      @entidade = Entidade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entidade_params
      params.require(:entidade).permit(:nif, :actividade_profissional,
                                        utilizador_attributes:
                                            [:nome, :email, :password, :password_confirmation, :foto,
                                              :morada, :codigo_postal, :contactos,
                                              :apresentacao, :localidade, :pagina, :id])
    end
end

app/helpers/entidades_helper.rb
module EntidadesHelper
end

app/views/entidades/_candidatos_interessados.html.erb
<h2>Candidatos interessados</h2>

<div class="interessados">
  <% @current_user.interessados.each do |u| %>
    <table>
      <tbody>
        <tr>
          <td style="vertical-align: top;">
            <div>
                <%= image_tag u.foto.url if u.foto? %>
            </div>
          </td>
          <td>
            <div class="crop">
              <div><strong><%= link_to u.nome, candidato_path(u.meta_id) %></strong></div>
              <div><%= u.meta.area_profissional %></div>
              <div><%= u.meta.experiencia_profissional %></div>
              <div><%= u.meta.habilitacoes_literarias %></div>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  <% end %>
</div>

app/views/entidades/_entidade.html.erb
<tr>
  <td style="vertical-align: top;">
    <div>
      <%= image_tag entidade.utilizador.foto.url if entidade.utilizador.foto? %>
    </div>
    <div>
      <% if current_user.meta_type == "Candidato" %>
        <% @utilizador_showing = entidade.utilizador %>
        <%= render 'utilizadores/interesse_form' %>
      <% end %>
    </div>
  </td>
  <td>
    <div class="crop">
      <div><strong><%= link_to entidade.utilizador.nome, entidade_path(entidade.utilizador.meta_id) %></strong></div>
      <div><%= entidade.actividade_profissional %></div>
      <div><%= entidade.utilizador.apresentacao %></div>
    </div>
  </td>
</tr>

app/views/entidades/_form.html.erb
<%= form_for(entidade) do |f| %>
  <% if entidade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entidade.errors.count, "error") %> prohibited this entidade from being saved:</h2>

      <ul>
      <% entidade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.fields_for :utilizador do |p| %>
    <%= render 'utilizadores/form_fields', f:  p  %>
  <% end %>

  <div class="field">
    <%= f.label :nif %>
    <%= f.text_field :nif %>
  </div>

  <div class="field">
    <%= f.label :actividade_profissional %>
    <%= f.text_field :actividade_profissional %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entidades/_historico.html.erb
<h2>Histórico</h2>

app/views/entidades/_meu_perfil.html.erb
<div>
  <div class="col-md-6">
    <%= render 'entidades/ofertas' %>
  </div>
  <div class="col-md-6">
    <%= render 'utilizadores/editar_perfil' %>
  </div>
</div>

<div>
  <!-- <div class="col-md-6">
    <%= render 'entidades/historico' %>
  </div> -->
  <div class="col-md-6">
    <%= render 'entidades/candidatos_interessados' %>
  </div>
</div>

app/views/entidades/_ofertas.html.erb
<h2>Ofertas</h2>

<div class="interessados">
  <% @current_user.meta.oferta_de_empregos.each do |o| %>
    <table>
      <tbody>
        <tr>
          <td style="vertical-align: top;">
            <div>
                <%= image_tag o.foto.url if o.foto? %>
            </div>
          </td>
          <td>
            <div class="crop">
              <div><strong><%= link_to o.titulo, oferta_de_emprego_path(o.id) %></strong></div>
              <div><%= o.validade_inicio %> a <%= o.validade_fim %></div>
              <div><%= o.empresa %></div>
              <div><%= o.descricao %></div>
            </div>
            <%= link_to "Editar", edit_oferta_de_emprego_path(o.id), class: "btn btn-default btn-xs" %>
            <%= link_to "Cancelar", oferta_de_emprego_path(o), class: "btn btn-default btn-xs",
                        data: {:confirm => "Tem a certeza?"}, :method => :delete %>
          </td>
        </tr>
      </tbody>
    </table>
  <% end %>
</div>

<%= link_to "Inserir Oferta", new_oferta_de_emprego_path, class: "btn btn-default" %>

app/views/entidades/_ultimas_empresas.html.erb
<h2>Últimas Empresas</h2>
<div class="interessados">
  <% @ultimas_empresas.each do |e| %>
    <table>
      <tbody>
        <tr>
          <td style="vertical-align: top;">
            <div>
                <%= image_tag e.utilizador.foto.url if e.utilizador.foto? %>
            </div>
          </td>
          <td>
            <div class="crop">
              <div><strong><%= link_to e.utilizador.nome, entidade_path(e.id) %></strong></div>
              <div><%= e.utilizador.apresentacao %></div>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  <% end %>
  <div style="margin-left: 1%"><strong><%= link_to "Ver todas as empresas", entidades_path %></strong></div>
</div>

app/views/entidades/_ultimas_ofertas.html.erb
<h2>Últimas Ofertas</h2>
<div class="interessados">
  <% @ultimas_ofertas.each do |o| %>
    <table>
      <tbody>
        <tr>
          <td style="vertical-align: top;">
            <div>
                <%= image_tag o.foto.url if o.foto? %>
            </div>
          </td>
          <td>
            <div class="crop">
              <div><strong><%= link_to o.titulo, oferta_de_emprego_path(o.id) %></strong></div>
              <div><%= o.validade_inicio %> a <%= o.validade_fim %></div>
              <div><%= o.empresa %></div>
              <div><%= o.descricao %></div>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  <% end %>
  <div style="margin-left: 1%"><strong><%= link_to "Ver todas as ofertas", oferta_de_empregos_path %></strong></div>
</div>

app/views/entidades/edit.html.erb
<h1>Editar Entidade</h1>

<%= render 'form', utilizador: @utilizador, entidade: @entidade %>

<%= link_to 'Show', @entidade %> |
<%= link_to 'Back', entidades_path %>

app/views/entidades/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Entidades</h1>

<div class="interessados">
  <table>
    <tbody>
      <%= render @entidades %>
      <%= will_paginate @entidades %>
    </tbody>
  </table>
  <%= will_paginate @entidades %>
</div>

app/views/entidades/new.html.erb
<h1>Nova Entidade</h1>

<%= render 'form', entidade: @entidade %>

<%= link_to 'Back', entidades_path %>

app/views/entidades/show.html.erb
<p id="notice"><%= notice %></p>

<% @utilizador_showing = @entidade.utilizador %>

<div class="col-md-4" style="text-align: center">
  <aside>
    <h2><%= @utilizador_showing.nome %></h2>
    <span class="content">
        <%= image_tag @utilizador_showing.foto.url if @utilizador_showing.foto? %>
    </span>
    <br>
    <% if current_user.meta_type == "Candidato" %>
      <%= render 'utilizadores/interesse_form' %>
    <% end %>
    <% if authorized_to_view_elements?("Entidade") %>
      <%= link_to "Editar", edit_entidade_path(@entidade), class: "btn btn-default" %>
    <% end %>
  </aside>
</div>


<div class="col-md-8">
  <p>
    <%= @utilizador_showing.apresentacao %><br><br>
    <strong>Actividade Profissional</strong><br>
    <%= @entidade.actividade_profissional %>
  </p>

  <p>
    <strong>Morada</strong><br>
    <%= @utilizador_showing.morada %><br>
    <%= @utilizador_showing.codigo_postal %> <%= @utilizador_showing.localidade %>
  </p>

  <p>
    <strong>Contactos</strong>
    <%= @utilizador_showing.contactos %><br>
    <%= @utilizador_showing.email %>
  </p>

  <p>
    <strong><%= link_to @utilizador_showing.pagina, "http://#{@utilizador_showing.pagina}" %></strong>
  </p>