config/routes.rb
Rails.application.routes.draw do
  # get 'sessions/new'

  resources :utilizadores
  resources :relationships, only: [:create, :destroy]
  resources :candidatos
  resources :entidades
  resources :oferta_de_empregos
  root    'static_pages#home'
  get     '/alterar_password',  to: 'utilizadores#alterar_password'
  get     '/meu_perfil',        to: 'static_pages#meu_perfil'
  get     '/registo',           to: 'static_pages#registo'
  get     '/login',             to: 'sessions#new'
  post    '/login',             to: 'sessions#create'
  delete  '/logout',            to: 'sessions#destroy'
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Bolsa de Emprego", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to current_user.nome, meu_perfil_path %></li>
          <li><%= link_to "Log out", logout_path, method: "delete" %></li>
        <% else %>
          <li><%= link_to "Registar-me", registo_path %></li>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Entidades", entidades_path %></li>
        <li><%= link_to "Candidatos", candidatos_path %></li>
        <li><%= link_to "Ofertas", oferta_de_empregos_path %></li>
        <li><%= link_to "Notícias", '#' %></li>
        <li><%= link_to "Users", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bolsa De Emprego</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <!-- <div class="alert alert-<%= message_type %>"><%= message %></div> -->
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>