config/routes.rb
Rails.application.routes.draw do
  # get 'sessions/new'

  resources :utilizadores
  resources :relationships, only: [:create, :destroy]
  resources :candidatos
  resources :entidades
  resources :oferta_de_empregos
  root    'static_pages#home'
  get     '/alterar_password',  to: 'utilizadores#alterar_password'
  get     '/meu_perfil',        to: 'static_pages#meu_perfil'
  get     '/registo',           to: 'static_pages#registo'
  get     '/login',             to: 'sessions#new'
  post    '/login',             to: 'sessions#create'
  delete  '/logout',            to: 'sessions#destroy'
end

app/controllers/utilizadores_controller.rb
class UtilizadoresController < ApplicationController
  before_action :set_utilizador, only: [:show, :edit, :update, :destroy]

  # GET /utilizadores
  # GET /utilizadores.json
  def index
    if current_user.meta_type != "Admin"
      redirect_to root_path
    end
    # @utilizadores = Utilizador.all
  end

  # GET /utilizadores/1
  # GET /utilizadores/1.json
  def show
    if current_user.meta_type != "Admin"
      redirect_to root_path
    end
  end

  # GET /utilizadores/new
  def new
    if current_user.meta_type != "Admin"
      redirect_to root_path
    end
    @utilizador = Utilizador.new
  end

  # GET /utilizadores/1/edit
  def edit
    if current_user.meta_type != "Admin"
      redirect_to root_path
    end
  end

  # POST /utilizadores
  # POST /utilizadores.json
  def create
    @utilizador = Utilizador.new(utilizador_params)

    respond_to do |format|
      if @utilizador.save
        format.html { redirect_to @utilizador, notice: 'Utilizador criado com sucesso.' }
        format.json { render :show, status: :created, location: @utilizador }
      else
        format.html { render :new }
        format.json { render json: @utilizador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /utilizadores/1
  # PATCH/PUT /utilizadores/1.json
  def update
    respond_to do |format|
      if params[:utilizador].has_key?("password_actual")
        if params[:utilizador][:password] != params[:utilizador][:password_confirmation]
          format.html { redirect_to root_path, notice: 'Nova Password e Confirmação da Password têm de ser iguais.'}
        end
        if !!@utilizador.authenticate(params[:utilizador][:password_actual])
          params[:utilizador].except(:password_actual)
          if @utilizador.update(utilizador_params)
            format.html { redirect_to root_path, notice: 'Password alterada com sucesso.'}
          end
        else
          format.html { redirect_to root_path, notice: 'Password actual errada.' }
        end
      else
        if @utilizador.update(utilizador_params)
          format.html { redirect_to @utilizador, notice: 'Utilizador actualizado com sucesso.' }
          format.json { render :show, status: :ok, location: @utilizador }
        else
          format.html { render :edit }
          format.json { render json: @utilizador.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def alterar_password
    @utilizador = current_user
  end

  # DELETE /utilizadores/1
  # DELETE /utilizadores/1.json
  def destroy
    @utilizador.destroy
    respond_to do |format|
      format.html { redirect_to utilizadores_url, notice: 'Utilizador was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_utilizador
      @utilizador = Utilizador.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def utilizador_params
      params.require(:utilizador).permit(:nome, :email, :password, :password_confirmation,
                                          :foto, :morada, :codigo_postal, :contactos,
                                          :apresentacao, :localidade, :pagina,
                                          :user_profile_id, :user_profile_type)
    end

    def correct_user
      @user = Utilizador.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/utilizadores_helper.rb
module UtilizadoresHelper
end

app/views/utilizadores/_criar_interesse.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :sobre_interesse_id, @utilizador_showing.id %></div>
  <%= f.submit "Interessado/a", class: "btn btn-primary" %>
<% end %>

app/views/utilizadores/_editar_perfil.html.erb
<h2><%= @cu.meta_type %></h2>
<% if @cu.meta_type == "Candidato" %>
  <%= link_to "Editar Dados", edit_candidato_path(@cu.meta), class: "btn btn-default" %>
<% else %>
  <% if @cu.meta_type == "Entidade" %>
    <%= link_to "Editar Dados", edit_entidade_path(@cu.meta), class: "btn btn-default" %>
  <% end %>
<% end %>
<%= link_to "Alterar Password", alterar_password_path, class: "btn btn-default" %>

app/views/utilizadores/_form.html.erb
<%= form_for(utilizador) do |f| %>
  <% if utilizador.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(utilizador.errors.count, "error") %> prohibited this utilizador from being saved:</h2>

      <ul>
      <% utilizador.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= render 'form_fields' %>

  <div class="field">
    <%= f.label :user_profile_id %>
    <%= f.number_field :user_profile_id %>
  </div>

  <div class="field">
    <%= f.label :user_profile_type %>
    <%= f.text_field :user_profile_type %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/utilizadores/_form_fields.html.erb
<div class="field">
  <%= f.label :nome %>
  <%= f.text_field :nome %>
</div>

<div class="field">
  <%= f.label :email %>
  <%= f.text_field :email %>
</div>

<% if params[:action] == "new" || params[:action] == "create" %>
  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>
<% end %>

<div class="picture">
  <%= f.file_field :foto, accept: 'image/jpeg,image/gif,image/png' %>
</div>

<div class="field">
  <%= f.label :morada %>
  <%= f.text_area :morada %>
</div>

<div class="field">
  <%= f.label :codigo_postal %>
  <%= f.text_field :codigo_postal %>
</div>

<div class="field">
  <%= f.label :contactos %>
  <%= f.text_field :contactos %>
</div>

<div class="field">
  <%= f.label :apresentacao %>
  <%= f.text_area :apresentacao %>
</div>

<div class="field">
  <%= f.label :localidade %>
  <%= f.text_field :localidade %>
</div>

<div class="field">
  <%= f.label :pagina %>
  <%= f.text_field :pagina %>
</div>

app/views/utilizadores/_interesse_form.html.erb
<div id="interesse_form">
  <% if current_user.interessado_em?(@utilizador_showing) %>
    <%= render 'utilizadores/remover_interesse' %>
  <% else %>
    <%= render 'utilizadores/criar_interesse' %>
  <% end %>
</div>

app/views/utilizadores/_remover_interesse.html.erb
<%= form_for(current_user.active_relationships.find_by(sobre_interesse_id: @utilizador_showing.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Anular Interesse", class: "btn" %>
<% end %>

app/views/utilizadores/_show.html.erb
<p>
  <strong>Nome:</strong>
  <%= user.nome %>
</p>

<p>
  <strong>Email:</strong>
  <%= user.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= user.password_digest %>
</p>

<span class="content">
    <%= image_tag user.foto.url if user.foto? %>
</span>

<p>
  <strong>Morada:</strong>
  <%= user.morada %>
</p>

<p>
  <strong>Codigo postal:</strong>
  <%= user.codigo_postal %>
</p>

<p>
  <strong>Contactos:</strong>
  <%= user.contactos %>
</p>

<p>
  <strong>Apresentacao:</strong>
  <%= user.apresentacao %>
</p>

<p>
  <strong>Localidade:</strong>
  <%= user.localidade %>
</p>

<p>
  <strong>Pagina:</strong>
  <%= user.pagina %>
</p>

<p>
  <strong>User profile:</strong>
  <%= user.meta_id %>
</p>

<p>
  <strong>User profile type:</strong>
  <%= user.meta_type %>
</p>

app/views/utilizadores/alterar_password.html.erb
<%= form_for(@utilizador) do |f| %>
  <% if @utilizador.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(utilizador.errors.count, "error") %> prohibited this utilizador from being saved:</h2>
      <ul>
      <% utilizador.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h2>Alterar Password</h2>
  <strong>Nome</strong>
  <h4><%= @utilizador.nome %></h4>

  <div class="field">
    <%= f.label "Password Actual" %>
    <%= f.password_field :password_actual %>
  </div>

  <div class="field">
    <%= f.label "Nova Password" %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label "Confirmação da Password" %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit "Alterar Password" %>
  </div>

<% end %>

app/views/utilizadores/edit.html.erb
<h1>Editing Utilizador</h1>

<%= render 'form', utilizador: @utilizador %>

<%= link_to 'Show', @utilizador %> |
<%= link_to 'Back', utilizadores_path %>

app/views/utilizadores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Utilizadores</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Password digest</th>
      <th>Foto</th>
      <th>Morada</th>
      <th>Codigo postal</th>
      <th>Contactos</th>
      <th>Apresentacao</th>
      <th>Localidade</th>
      <th>Pagina</th>
      <th>User profile</th>
      <th>User profile type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @utilizadores.each do |utilizador| %>
      <tr>
        <td><%= utilizador.nome %></td>
        <td><%= utilizador.email %></td>
        <td><%= utilizador.password_digest %></td>
        <td><%= utilizador.foto %></td>
        <td><%= utilizador.morada %></td>
        <td><%= utilizador.codigo_postal %></td>
        <td><%= utilizador.contactos %></td>
        <td><%= utilizador.apresentacao %></td>
        <td><%= utilizador.localidade %></td>
        <td><%= utilizador.pagina %></td>
        <td><%= utilizador.user_profile_id %></td>
        <td><%= utilizador.user_profile_type %></td>
        <td><%= link_to 'Show', utilizador %></td>
        <td><%= link_to 'Edit', edit_utilizador_path(utilizador) %></td>
        <td><%= link_to 'Destroy', utilizador, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Utilizador', new_utilizador_path %>

app/views/utilizadores/new.html.erb
<h1>New Utilizador</h1>

<%= render 'form', utilizador: @utilizador %>

<%= link_to 'Back', utilizadores_path %>

app/views/utilizadores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @utilizador.nome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @utilizador.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @utilizador.password_digest %>
</p>

<span class="content">
    <%= image_tag @utilizador.foto.url if @candidato.utilizador.foto? %>
</span>

<p>
  <strong>Morada:</strong>
  <%= @utilizador.morada %>
</p>

<p>
  <strong>Codigo postal:</strong>
  <%= @utilizador.codigo_postal %>
</p>

<p>
  <strong>Contactos:</strong>
  <%= @utilizador.contactos %>
</p>

<p>
  <strong>Apresentacao:</strong>
  <%= @utilizador.apresentacao %>
</p>

<p>
  <strong>Localidade:</strong>
  <%= @utilizador.localidade %>
</p>

<p>
  <strong>Pagina:</strong>
  <%= @utilizador.pagina %>
</p>

<p>
  <strong>User profile:</strong>
  <%= @utilizador.user_profile_id %>
</p>

<p>
  <strong>User profile type:</strong>
  <%= @utilizador.user_profile_type %>
</p>

<%= link_to 'Edit', edit_utilizador_path(@utilizador) %> |
<%= link_to 'Back', utilizadores_path %>